### ISSUE TITLE
user profile data mismatch (twitter)

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsmeet-click/letsmeet.click#9]
When I use Twitter, it also mismatches the data:

```
First name:  Thomas
Last name: J. Waldmann     ---> nope
Username: ThomasJWaldmann
Email:
Password set: no
```

**Comment by ulope** [comment]
Fixed

**Comment by ThomasWaldmann** [comment]
Not fixed, please reopen.

**Comment by ulope** [comment]
Unfortunately Twitter's oauth implementation only supplies a single "name" field so `python-social-auth` is forced to guess which parts are first and last name.

We will add profile editing which should allow users to fix problems like this themselves.

**Comment by ThomasWaldmann** [comment]
Thanks for the explanation, but you still need to reopen it, it is not fixed yet.
